### PR TITLE
Remove the ffwd-http-reporter

### PR DESCRIPTION
**Pull request by klaraward**
Due to the problems with the shaded packages in older versions of ffwd-http-client, 
and to the fact that ffwd-http-reporter does not seem to be used anywhere (within Spotify),
I suggest (and I think this is not a new idea), that this module is removed.

One option, if this seems to daring, is to just remove it from the semantic-metrics-bom.

This is a prerequisite for https://github.com/spotify/apollo/pull/342

### CODE REVIEW

**Review by ao2017 — APPROVED** [review]

**Review by lepistone — APPROVED** [review]
Thank you!

**Comment by samfadrigalan** [comment]
I took the following steps to test the changes and verified that metrics are able to flow through Heroic for producers using this PR's version of semantic-metrics

- I pulled the PR changes and ran `mvn clean package`. This updated the `1.1.8-SNAPSHOT` in my `~/.m2/repository/com/spotify/metrics`. I verified the mvn packages by checking if they reflected the PR changes.
```
## ex. check that ffwd-http-reporter is not in the parent pom
$> cat semantic-metrics-parent/1.1.7/semantic-metrics-parent-1.1.7.pom | grep ffwd-http-reporter
    <module>ffwd-http-reporter</module>
        <artifactId>semantic-metrics-ffwd-http-reporter</artifactId>
$> cat semantic-metrics-parent/1.1.8-SNAPSHOT/semantic-metrics-parent-1.1.8-SNAPSHOT.pom | grep ffwd-http-reporter
$ [0|1]>
```
- I ran `test-tracing-app` with `<semantic-metrics.version>1.1.8-SNAPSHOT</semantic-metrics.version>`.
Screen Shot 2021-05-04 at 10 19 03 AM

- I ran `ffwd` on my machine and generated counter metrics via `test-tracing-app` which is now using this PR's semantic-metrics version.

- Verified that the metrics are visible on [grafana](https://grafana.spotify.net/d/oC4XX59Gz/quick-test?orgId=1&fullscreen&panelId=2&edit&from=now-15m&to=now).
Screen Shot 2021-05-04 at 10 25 41 AM

**Comment by ao2017** [comment]
> I took the following steps to test the changes and verified that metrics are able to flow through Heroic for producers using this PR's version of semantic-metrics
> 
> * I pulled the PR changes and ran `mvn clean package`. This updated the `1.1.8-SNAPSHOT` in my `~/.m2/repository/com/spotify/metrics`. I verified the mvn packages by checking if they reflected the PR changes.
> 
> ```
> ## ex. check that ffwd-http-reporter is not in the parent pom
> $> cat semantic-metrics-parent/1.1.7/semantic-metrics-parent-1.1.7.pom | grep ffwd-http-reporter
>     <module>ffwd-http-reporter</module>
>         <artifactId>semantic-metrics-ffwd-http-reporter</artifactId>
> $> cat semantic-metrics-parent/1.1.8-SNAPSHOT/semantic-metrics-parent-1.1.8-SNAPSHOT.pom | grep ffwd-http-reporter
> $ [0|1]>
> ```
> 
> * I ran `test-tracing-app` with `<semantic-metrics.version>1.1.8-SNAPSHOT</semantic-metrics.version>`.
> 
> Screen Shot 2021-05-04 at 10 19 03 AM
> 
> * I ran `ffwd` on my machine and generated counter metrics via `test-tracing-app` which is now using this PR's semantic-metrics version.
> * Verified that the metrics are visible on [grafana](https://grafana.spotify.net/d/oC4XX59Gz/quick-test?orgId=1&fullscreen&panelId=2&edit&from=now-15m&to=now).
> 
> Screen Shot 2021-05-04 at 10 25 41 AM

The result of the test looks good, but the risks of this PR are outside of semantics metrics and ffwd. The bad import statements are the concerns.    Per our last week conversation, I will go ahead and merge the PR.

**Comment by klaraward** [comment]
Will you also make a new 1.1.8 release with this?

**Pull request merged**
